services:
  juno-satellite:
    image: junobuild/satellite:0.0.57
    ports:
      - 5987:5987
    volumes:
      - juno_satellite_passkey:/juno/.juno
      - ./juno.dev.config.json:/juno/juno.dev.config.json
      - ./target/deploy:/juno/target/deploy/

volumes:
  juno_satellite_passkey:
