name: Checks

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run lint -- --max-warnings 0

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: npm run build

  may-merge:
    needs: ['build', 'lint']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
